require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ArquivosController do

  def mock_arquivo(stubs={})
    @mock_arquivo ||= mock_model(Arquivo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all arquivos as @arquivos" do
      Arquivo.stub(:all) { [mock_arquivo] }
      get :index
      assigns(:arquivos).should eq([mock_arquivo])
    end
  end

  describe "GET show" do
    it "assigns the requested arquivo as @arquivo" do
      Arquivo.stub(:find).with("37") { mock_arquivo }
      get :show, :id => "37"
      assigns(:arquivo).should be(mock_arquivo)
    end
  end

  describe "GET new" do
    it "assigns a new arquivo as @arquivo" do
      Arquivo.stub(:new) { mock_arquivo }
      get :new
      assigns(:arquivo).should be(mock_arquivo)
    end
  end

  describe "GET edit" do
    it "assigns the requested arquivo as @arquivo" do
      Arquivo.stub(:find).with("37") { mock_arquivo }
      get :edit, :id => "37"
      assigns(:arquivo).should be(mock_arquivo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created arquivo as @arquivo" do
        Arquivo.stub(:new).with({'these' => 'params'}) { mock_arquivo(:save => true) }
        post :create, :arquivo => {'these' => 'params'}
        assigns(:arquivo).should be(mock_arquivo)
      end

      it "redirects to the created arquivo" do
        Arquivo.stub(:new) { mock_arquivo(:save => true) }
        post :create, :arquivo => {}
        response.should redirect_to(arquivo_url(mock_arquivo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved arquivo as @arquivo" do
        Arquivo.stub(:new).with({'these' => 'params'}) { mock_arquivo(:save => false) }
        post :create, :arquivo => {'these' => 'params'}
        assigns(:arquivo).should be(mock_arquivo)
      end

      it "re-renders the 'new' template" do
        Arquivo.stub(:new) { mock_arquivo(:save => false) }
        post :create, :arquivo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested arquivo" do
        Arquivo.stub(:find).with("37") { mock_arquivo }
        mock_arquivo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :arquivo => {'these' => 'params'}
      end

      it "assigns the requested arquivo as @arquivo" do
        Arquivo.stub(:find) { mock_arquivo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:arquivo).should be(mock_arquivo)
      end

      it "redirects to the arquivo" do
        Arquivo.stub(:find) { mock_arquivo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(arquivo_url(mock_arquivo))
      end
    end

    describe "with invalid params" do
      it "assigns the arquivo as @arquivo" do
        Arquivo.stub(:find) { mock_arquivo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:arquivo).should be(mock_arquivo)
      end

      it "re-renders the 'edit' template" do
        Arquivo.stub(:find) { mock_arquivo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested arquivo" do
      Arquivo.stub(:find).with("37") { mock_arquivo }
      mock_arquivo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the arquivos list" do
      Arquivo.stub(:find) { mock_arquivo }
      delete :destroy, :id => "1"
      response.should redirect_to(arquivos_url)
    end
  end

end
