require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CandidatosController do

  def mock_candidato(stubs={})
    @mock_candidato ||= mock_model(Candidato, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all candidatos as @candidatos" do
      Candidato.stub(:all) { [mock_candidato] }
      get :index
      assigns(:candidatos).should eq([mock_candidato])
    end
  end

  describe "GET show" do
    it "assigns the requested candidato as @candidato" do
      Candidato.stub(:find).with("37") { mock_candidato }
      get :show, :id => "37"
      assigns(:candidato).should be(mock_candidato)
    end
  end

  describe "GET new" do
    it "assigns a new candidato as @candidato" do
      Candidato.stub(:new) { mock_candidato }
      get :new
      assigns(:candidato).should be(mock_candidato)
    end
  end

  describe "GET edit" do
    it "assigns the requested candidato as @candidato" do
      Candidato.stub(:find).with("37") { mock_candidato }
      get :edit, :id => "37"
      assigns(:candidato).should be(mock_candidato)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created candidato as @candidato" do
        Candidato.stub(:new).with({'these' => 'params'}) { mock_candidato(:save => true) }
        post :create, :candidato => {'these' => 'params'}
        assigns(:candidato).should be(mock_candidato)
      end

      it "redirects to the created candidato" do
        Candidato.stub(:new) { mock_candidato(:save => true) }
        post :create, :candidato => {}
        response.should redirect_to(candidato_url(mock_candidato))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved candidato as @candidato" do
        Candidato.stub(:new).with({'these' => 'params'}) { mock_candidato(:save => false) }
        post :create, :candidato => {'these' => 'params'}
        assigns(:candidato).should be(mock_candidato)
      end

      it "re-renders the 'new' template" do
        Candidato.stub(:new) { mock_candidato(:save => false) }
        post :create, :candidato => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested candidato" do
        Candidato.stub(:find).with("37") { mock_candidato }
        mock_candidato.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :candidato => {'these' => 'params'}
      end

      it "assigns the requested candidato as @candidato" do
        Candidato.stub(:find) { mock_candidato(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:candidato).should be(mock_candidato)
      end

      it "redirects to the candidato" do
        Candidato.stub(:find) { mock_candidato(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(candidato_url(mock_candidato))
      end
    end

    describe "with invalid params" do
      it "assigns the candidato as @candidato" do
        Candidato.stub(:find) { mock_candidato(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:candidato).should be(mock_candidato)
      end

      it "re-renders the 'edit' template" do
        Candidato.stub(:find) { mock_candidato(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested candidato" do
      Candidato.stub(:find).with("37") { mock_candidato }
      mock_candidato.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the candidatos list" do
      Candidato.stub(:find) { mock_candidato }
      delete :destroy, :id => "1"
      response.should redirect_to(candidatos_url)
    end
  end

end
