require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ConcursosController do

  def mock_concurso(stubs={})
    @mock_concurso ||= mock_model(Concurso, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all concursos as @concursos" do
      Concurso.stub(:all) { [mock_concurso] }
      get :index
      assigns(:concursos).should eq([mock_concurso])
    end
  end

  describe "GET show" do
    it "assigns the requested concurso as @concurso" do
      Concurso.stub(:find).with("37") { mock_concurso }
      get :show, :id => "37"
      assigns(:concurso).should be(mock_concurso)
    end
  end

  describe "GET new" do
    it "assigns a new concurso as @concurso" do
      Concurso.stub(:new) { mock_concurso }
      get :new
      assigns(:concurso).should be(mock_concurso)
    end
  end

  describe "GET edit" do
    it "assigns the requested concurso as @concurso" do
      Concurso.stub(:find).with("37") { mock_concurso }
      get :edit, :id => "37"
      assigns(:concurso).should be(mock_concurso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created concurso as @concurso" do
        Concurso.stub(:new).with({'these' => 'params'}) { mock_concurso(:save => true) }
        post :create, :concurso => {'these' => 'params'}
        assigns(:concurso).should be(mock_concurso)
      end

      it "redirects to the created concurso" do
        Concurso.stub(:new) { mock_concurso(:save => true) }
        post :create, :concurso => {}
        response.should redirect_to(concurso_url(mock_concurso))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved concurso as @concurso" do
        Concurso.stub(:new).with({'these' => 'params'}) { mock_concurso(:save => false) }
        post :create, :concurso => {'these' => 'params'}
        assigns(:concurso).should be(mock_concurso)
      end

      it "re-renders the 'new' template" do
        Concurso.stub(:new) { mock_concurso(:save => false) }
        post :create, :concurso => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested concurso" do
        Concurso.stub(:find).with("37") { mock_concurso }
        mock_concurso.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :concurso => {'these' => 'params'}
      end

      it "assigns the requested concurso as @concurso" do
        Concurso.stub(:find) { mock_concurso(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:concurso).should be(mock_concurso)
      end

      it "redirects to the concurso" do
        Concurso.stub(:find) { mock_concurso(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(concurso_url(mock_concurso))
      end
    end

    describe "with invalid params" do
      it "assigns the concurso as @concurso" do
        Concurso.stub(:find) { mock_concurso(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:concurso).should be(mock_concurso)
      end

      it "re-renders the 'edit' template" do
        Concurso.stub(:find) { mock_concurso(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested concurso" do
      Concurso.stub(:find).with("37") { mock_concurso }
      mock_concurso.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the concursos list" do
      Concurso.stub(:find) { mock_concurso }
      delete :destroy, :id => "1"
      response.should redirect_to(concursos_url)
    end
  end

end
