require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FaculdadesController do

  def mock_faculdade(stubs={})
    @mock_faculdade ||= mock_model(Faculdade, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all faculdades as @faculdades" do
      Faculdade.stub(:all) { [mock_faculdade] }
      get :index
      assigns(:faculdades).should eq([mock_faculdade])
    end
  end

  describe "GET show" do
    it "assigns the requested faculdade as @faculdade" do
      Faculdade.stub(:find).with("37") { mock_faculdade }
      get :show, :id => "37"
      assigns(:faculdade).should be(mock_faculdade)
    end
  end

  describe "GET new" do
    it "assigns a new faculdade as @faculdade" do
      Faculdade.stub(:new) { mock_faculdade }
      get :new
      assigns(:faculdade).should be(mock_faculdade)
    end
  end

  describe "GET edit" do
    it "assigns the requested faculdade as @faculdade" do
      Faculdade.stub(:find).with("37") { mock_faculdade }
      get :edit, :id => "37"
      assigns(:faculdade).should be(mock_faculdade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created faculdade as @faculdade" do
        Faculdade.stub(:new).with({'these' => 'params'}) { mock_faculdade(:save => true) }
        post :create, :faculdade => {'these' => 'params'}
        assigns(:faculdade).should be(mock_faculdade)
      end

      it "redirects to the created faculdade" do
        Faculdade.stub(:new) { mock_faculdade(:save => true) }
        post :create, :faculdade => {}
        response.should redirect_to(faculdade_url(mock_faculdade))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved faculdade as @faculdade" do
        Faculdade.stub(:new).with({'these' => 'params'}) { mock_faculdade(:save => false) }
        post :create, :faculdade => {'these' => 'params'}
        assigns(:faculdade).should be(mock_faculdade)
      end

      it "re-renders the 'new' template" do
        Faculdade.stub(:new) { mock_faculdade(:save => false) }
        post :create, :faculdade => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested faculdade" do
        Faculdade.stub(:find).with("37") { mock_faculdade }
        mock_faculdade.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :faculdade => {'these' => 'params'}
      end

      it "assigns the requested faculdade as @faculdade" do
        Faculdade.stub(:find) { mock_faculdade(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:faculdade).should be(mock_faculdade)
      end

      it "redirects to the faculdade" do
        Faculdade.stub(:find) { mock_faculdade(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(faculdade_url(mock_faculdade))
      end
    end

    describe "with invalid params" do
      it "assigns the faculdade as @faculdade" do
        Faculdade.stub(:find) { mock_faculdade(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:faculdade).should be(mock_faculdade)
      end

      it "re-renders the 'edit' template" do
        Faculdade.stub(:find) { mock_faculdade(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested faculdade" do
      Faculdade.stub(:find).with("37") { mock_faculdade }
      mock_faculdade.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the faculdades list" do
      Faculdade.stub(:find) { mock_faculdade }
      delete :destroy, :id => "1"
      response.should redirect_to(faculdades_url)
    end
  end

end
