require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NoticiasController do

  def mock_noticia(stubs={})
    @mock_noticia ||= mock_model(Noticia, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all noticias as @noticias" do
      Noticia.stub(:all) { [mock_noticia] }
      get :index
      assigns(:noticias).should eq([mock_noticia])
    end
  end

  describe "GET show" do
    it "assigns the requested noticia as @noticia" do
      Noticia.stub(:find).with("37") { mock_noticia }
      get :show, :id => "37"
      assigns(:noticia).should be(mock_noticia)
    end
  end

  describe "GET new" do
    it "assigns a new noticia as @noticia" do
      Noticia.stub(:new) { mock_noticia }
      get :new
      assigns(:noticia).should be(mock_noticia)
    end
  end

  describe "GET edit" do
    it "assigns the requested noticia as @noticia" do
      Noticia.stub(:find).with("37") { mock_noticia }
      get :edit, :id => "37"
      assigns(:noticia).should be(mock_noticia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created noticia as @noticia" do
        Noticia.stub(:new).with({'these' => 'params'}) { mock_noticia(:save => true) }
        post :create, :noticia => {'these' => 'params'}
        assigns(:noticia).should be(mock_noticia)
      end

      it "redirects to the created noticia" do
        Noticia.stub(:new) { mock_noticia(:save => true) }
        post :create, :noticia => {}
        response.should redirect_to(noticia_url(mock_noticia))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved noticia as @noticia" do
        Noticia.stub(:new).with({'these' => 'params'}) { mock_noticia(:save => false) }
        post :create, :noticia => {'these' => 'params'}
        assigns(:noticia).should be(mock_noticia)
      end

      it "re-renders the 'new' template" do
        Noticia.stub(:new) { mock_noticia(:save => false) }
        post :create, :noticia => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested noticia" do
        Noticia.stub(:find).with("37") { mock_noticia }
        mock_noticia.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :noticia => {'these' => 'params'}
      end

      it "assigns the requested noticia as @noticia" do
        Noticia.stub(:find) { mock_noticia(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:noticia).should be(mock_noticia)
      end

      it "redirects to the noticia" do
        Noticia.stub(:find) { mock_noticia(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(noticia_url(mock_noticia))
      end
    end

    describe "with invalid params" do
      it "assigns the noticia as @noticia" do
        Noticia.stub(:find) { mock_noticia(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:noticia).should be(mock_noticia)
      end

      it "re-renders the 'edit' template" do
        Noticia.stub(:find) { mock_noticia(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested noticia" do
      Noticia.stub(:find).with("37") { mock_noticia }
      mock_noticia.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the noticias list" do
      Noticia.stub(:find) { mock_noticia }
      delete :destroy, :id => "1"
      response.should redirect_to(noticias_url)
    end
  end

end
