require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RelacionamentosController do

  def mock_relacionamento(stubs={})
    @mock_relacionamento ||= mock_model(Relacionamento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all relacionamentos as @relacionamentos" do
      Relacionamento.stub(:all) { [mock_relacionamento] }
      get :index
      assigns(:relacionamentos).should eq([mock_relacionamento])
    end
  end

  describe "GET show" do
    it "assigns the requested relacionamento as @relacionamento" do
      Relacionamento.stub(:find).with("37") { mock_relacionamento }
      get :show, :id => "37"
      assigns(:relacionamento).should be(mock_relacionamento)
    end
  end

  describe "GET new" do
    it "assigns a new relacionamento as @relacionamento" do
      Relacionamento.stub(:new) { mock_relacionamento }
      get :new
      assigns(:relacionamento).should be(mock_relacionamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested relacionamento as @relacionamento" do
      Relacionamento.stub(:find).with("37") { mock_relacionamento }
      get :edit, :id => "37"
      assigns(:relacionamento).should be(mock_relacionamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created relacionamento as @relacionamento" do
        Relacionamento.stub(:new).with({'these' => 'params'}) { mock_relacionamento(:save => true) }
        post :create, :relacionamento => {'these' => 'params'}
        assigns(:relacionamento).should be(mock_relacionamento)
      end

      it "redirects to the created relacionamento" do
        Relacionamento.stub(:new) { mock_relacionamento(:save => true) }
        post :create, :relacionamento => {}
        response.should redirect_to(relacionamento_url(mock_relacionamento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relacionamento as @relacionamento" do
        Relacionamento.stub(:new).with({'these' => 'params'}) { mock_relacionamento(:save => false) }
        post :create, :relacionamento => {'these' => 'params'}
        assigns(:relacionamento).should be(mock_relacionamento)
      end

      it "re-renders the 'new' template" do
        Relacionamento.stub(:new) { mock_relacionamento(:save => false) }
        post :create, :relacionamento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relacionamento" do
        Relacionamento.stub(:find).with("37") { mock_relacionamento }
        mock_relacionamento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :relacionamento => {'these' => 'params'}
      end

      it "assigns the requested relacionamento as @relacionamento" do
        Relacionamento.stub(:find) { mock_relacionamento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:relacionamento).should be(mock_relacionamento)
      end

      it "redirects to the relacionamento" do
        Relacionamento.stub(:find) { mock_relacionamento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(relacionamento_url(mock_relacionamento))
      end
    end

    describe "with invalid params" do
      it "assigns the relacionamento as @relacionamento" do
        Relacionamento.stub(:find) { mock_relacionamento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:relacionamento).should be(mock_relacionamento)
      end

      it "re-renders the 'edit' template" do
        Relacionamento.stub(:find) { mock_relacionamento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relacionamento" do
      Relacionamento.stub(:find).with("37") { mock_relacionamento }
      mock_relacionamento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the relacionamentos list" do
      Relacionamento.stub(:find) { mock_relacionamento }
      delete :destroy, :id => "1"
      response.should redirect_to(relacionamentos_url)
    end
  end

end
